# Generated by Django 4.1.6 on 2023-02-04 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=200, verbose_name='Reference Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('module', models.CharField(max_length=255, verbose_name='Module')),
                ('status', models.CharField(choices=[('Open', 'open'), ('Acknowledged', 'Acknowledged'), ('Solved', 'Solved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_status', models.CharField(choices=[('Open', 'open'), ('Acknowledged', 'Acknowledged'), ('Solved', 'Solved'), ('Closed', 'Closed')], default='Open', max_length=50, verbose_name='Ticket Status')),
                ('message', models.TextField(verbose_name='Message')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_log_by', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_logs', to='ticket_support.supportticket', verbose_name='Ticket')),
            ],
        ),
    ]
