# Generated by Django 4.1.6 on 2023-02-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='added_by',
        ),
    ]
