# Generated by Django 4.1.6 on 2023-02-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_support', '0002_remove_supportticket_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlog',
            name='added_by',
        ),
    ]
